# Generated by Django 2.1.3 on 2018-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181130_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Warehouse Manager'), (2, 'Supplier'), (3, 'Warehouse Employee')], default=1),
        ),
    ]
