# Generated by Django 2.1.3 on 2018-11-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='qwert', max_length=50),
            preserve_default=False,
        ),
    ]
